<template>
  <div id="theme">
    <Title topic="Themes"/>

    <v-container class="hidden-sm-and-up">
      <v-layout column wrap>
        <v-flex xs12 md6 v-for="stat in cont" :key="stat.id" pa-1>
          <v-layout
            row
            wrap
            justify-center
            align-center
            fill-height
            class="pa-2"
            style="border-bottom: 4px solid #005386;"
          >
            <v-flex xs12 md3 justify-space-around>
              <v-img
                contain
                max-width="200px"
                :src="require('~/assets/img/Themes/' + stat.id + '.png')"
              ></v-img>
            </v-flex>
            <v-flex xs12 md7>
              <div v-for="it in stat.desc" :key="it">
                <p text-xs-left class="fontz grey--text text--darken-2">{{ it }}</p>
              </div>
            </v-flex>
            <v-flex xs12 text-xs-right>
              <v-spacer></v-spacer>
              <v-btn color="#3DA9EB" round outline router to="/Process/#themesel">Read More</v-btn>
            </v-flex>
          </v-layout>
        </v-flex>
      </v-layout>
    </v-container>

    <v-container class="hidden-xs-only">
      <v-layout row wrap>
        <v-flex xs6 md3 v-for="stat in 4" :key="stat" pa-3>
          <v-img
            class="image-hover-highlight"
            contain
            v-on:click.stop="diaClick(stat)"
            :src="require('~/assets/img/Themes/' + stat + '.png')"
          ></v-img>
          <v-dialog v-model="dialog" max-width="500px">
            <v-card class="pa-5 bord2">
              <v-template v-for="stat in cont" :key="stat.id">
                <v-layout row wrap justify-center text-xs-center v-if="stat.id == it">
                  <v-flex xs12>
                    <v-img
                      contain
                      max-height="330px"
                      :src="require('~/assets/img/Themes/' + stat.id + '.png')"
                    ></v-img>
                  </v-flex>
                  <v-flex xs12>
                    <div v-for="it in stat.desc" :key="it">
                      <p text-xs-left class="fontz grey--text text--darken-2">{{ it }}</p>
                    </div>
                  </v-flex>
                  <!-- <v-flex xs12 text-xs-right>
                    <v-spacer></v-spacer>
                    <v-btn
                      color="#3DA9EB"
                      round
                      outline
                      @click="this.dialog = ! this.dialog"                   
                      
                    >Read More</v-btn>
                  </v-flex> -->
                </v-layout>
              </v-template>
            </v-card>
          </v-dialog>
        </v-flex>
      </v-layout>
    </v-container>
  </div>
</template>

<script>
import Title from '@/components/Title'
import Subtitle from '@/components/Subtitle'

export default {
  components: {
    Title,
    Subtitle
  },
  methods: {
    diaClick(st) {
      this.it = st
      this.dialog = !this.dialog
    },
    dialbtn () {
      this.dialog = !this.dialog
      this.$route.push({ path: '/Process/#themesel'})
    }
  },

  data: () => {
    return {
      dialog: false,
      it: 1,
      cont: [
        {
          id: 1,
          desc: [
            'Even a small mobile connected the whole world. Think, Create/Recreate, Design, Simulate & Validate a product. Which should be smaller, lighter, faster, efficient and makes life easy. '
          ]
        },

        {
          id: 2,
          desc: [
            'In present scenario smart folks are using smart technologies. So can’t we create a smart way to produce energy?  A transition is needed to a more inclusive, sustainable, affordable and secure global energy system that provides solutions to global energy-related challenges, while creating value for business and society. These could be for Offices, homes, villages and remote areas.'
          ]
        },

        {
          id: 3,
          desc: [
            'Water is next big challenge for the world. It is a unique resource that underpins all drivers of growth – be it agricultural production, energy generation, industry or manufacturing. At the current rate, there will be a 40% gap between global water supply and demand by 2030. '
          ]
        },

        {
          id: 4,
          desc: [
            'Waste is the new beginning and Think green is new trend. It is a lesser known fact that industrial machines and automobiles can runs on liquid fuels generated by Plastic Waste. Evolve your imagination and device a mechanism. Which can utilize the solid, liquid, organic waste, recyclable waste and hazardous waste to generate wealth of country and wonder for world. '
          ]
        }
      ]
    }
  }
}
</script>

<style scoped>
.fontz {
  font-size: calc(12px + 4 * ((100vw - 320px) / 880));
  font-family: '3ds';
  font-weight: 500;
  line-height: 1.2;
  letter-spacing: -0.2px;
  /* 757575 424242*/
}
.bord {
  border: 2px solid #005386;
  border-radius: 30px;
  opacity: 0.9;
  box-shadow: 0 8px 12px 0 rgba(0, 0, 0, 0.3);
}
.v-dialog__content--active {
  background-color: rgba(0, 0, 0, 0.2) !important;
}

.bord2 {
  border: 5px solid #005386;
  /* border-radius: 30px!important; */
  opacity: 0.9;
  /* box-shadow: 0 8px 12px 0 rgba(0, 0, 0, 0.3); */
}

.image-hover-highlight {
  -webkit-transition: all 0.5s;
  transition: all 0.5s;
}
.image-hover-highlight:hover {
  border: 2px solid #005386;
  border-radius: 30px;
  background-color: white;
  cursor: pointer;
  opacity: 0.9;
  box-shadow: 0 6px 10px 0 rgba(0, 0, 0, 0.2);
  filter: brightness(130%);
  -webkit-filter: brightness(130%);
  -moz-filter: brightness(130%);
  -o-filter: brightness(130%);
  -ms-filter: brightness(130%);
  -webkit-transition: all 0.5s;
  transition: all 0.5s;
}
</style>
